export const siteMetadata = {
    title: 'Chethana | Personal Portfolio',
    author: 'Chethana Virajini',
    headerTitle: 'Chethana Virajini',
    description: 'Chethana is a results-driven software engineer with 1 year of experience in developing robust and scalable applications. With a strong foundation in computer science and a knack for staying up-to-date with the latest technologies, I thrive in dynamic environments where innovation is paramount.',
    language: 'en-us',
    theme: 'system',
    siteUrl: '',
    siteLogo: '',
    socialBanner: '',
    email: '',
    twitter: '',
    facebook: '',
    linkedin: '',
    Instagram: '',
    locale: 'en-US',
};